'use client';

import React, { useState, useRef, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useSessionStore } from '../store/sessionStore';
import { useRealtimeChat } from '../hooks/useRealtimeChat';
import {
  Upload,
  FileText,
  Download,
  X,
  Search,
  Tag,
  Clock,
  CheckCircle,
  AlertTriangle,
  Trash2,
  Eye,
  FolderOpen,
  Plus,
} from 'lucide-react';
import { DocumentInfo } from '../types';

interface UploadedDocument extends DocumentInfo {
  preview?: string;
  processing?: boolean;
  progress?: number;
}

export default function DocumentUploader() {
  const {
    documents,
    uploadingDocuments,
    theme,
    addDocument,
    removeDocument,
    setUploadingDocuments,
  } = useSessionStore();

  const { sendDocumentUpload, connectionStatus } = useRealtimeChat();
  const [isDragging, setIsDragging] = useState(false);
  const [selectedDocument, setSelectedDocument] = useState<UploadedDocument | null>(null);
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedTag, setSelectedTag] = useState<string>('all');
  const fileInputRef = useRef<HTMLInputElement>(null);

  // File type configuration
  const allowedTypes = {
    'application/pdf': { name: 'PDF', icon: '📄' },
    'application/msword': { name: 'Word', icon: '📝' },
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document': { name: 'Word', icon: '📝' },
    'text/plain': { name: 'Text', icon: '📄' },
    'application/vnd.ms-excel': { name: 'Excel', icon: '📊' },
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': { name: 'Excel', icon: '📊' },
  };

  const maxFileSize = 10 * 1024 * 1024; // 10MB

  // Get all unique tags from documents
  const allTags = Array.from(new Set(documents.flatMap(doc => doc.tags)));

  // Filter documents based on search and tag
  const filteredDocuments = documents.filter(doc => {
    const matchesSearch = doc.filename.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         doc.contentSummary?.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesTag = selectedTag === 'all' || doc.tags.includes(selectedTag);
    return matchesSearch && matchesTag;
  });

  // Handle file selection
  const handleFileSelect = useCallback((files: FileList | null) => {
    if (!files || files.length === 0) return;

    const file = files[0];

    // Validate file type
    if (!Object.keys(allowedTypes).includes(file.type)) {
      alert(`Unsupported file type: ${file.type}. Please use PDF, Word, or text files.`);
      return;
    }

    // Validate file size
    if (file.size > maxFileSize) {
      alert(`File too large: ${Math.round(file.size / 1024 / 1024)}MB. Maximum size is 10MB.`);
      return;
    }

    processFile(file);
  }, []);

  // Process file upload
  const processFile = async (file: File) => {
    setUploadingDocuments(true);

    // Read file as base64
    const reader = new FileReader();
    reader.onload = async (e) => {
      const base64Content = e.target?.result as string;

      // Create document object
      const newDoc: UploadedDocument = {
        filename: file.name,
        fileType: file.type,
        fileSize: file.size,
        contentSummary: 'Processing document...',
        tags: detectDocumentTags(file.name),
        uploadedAt: new Date(),
        processed: false,
        processing: true,
        progress: 0,
      };

      // Add to local store immediately for UI feedback
      addDocument(newDoc);

      // Simulate processing progress
      const progressInterval = setInterval(() => {
        setProcessingProgress(file.name, Math.min((newDoc.progress || 0) + 20, 90));
      }, 500);

      try {
        // Send to backend for processing
        sendDocumentUpload({
          filename: file.name,
          fileType: file.type,
          fileSize: file.size,
          content: base64Content,
          summary: '', // Will be generated by backend
        });

        // Complete processing
        clearInterval(progressInterval);
        setProcessingProgress(file.name, 100);

        setTimeout(() => {
          updateDocumentStatus(file.name, {
            processed: true,
            processing: false,
            progress: 100,
            contentSummary: 'Document processed successfully. AI analysis complete.',
          });
        }, 1000);

      } catch (error) {
        console.error('Document upload failed:', error);
        clearInterval(progressInterval);

        updateDocumentStatus(file.name, {
          processing: false,
          processed: false,
          contentSummary: 'Failed to process document. Please try again.',
        });
      } finally {
        setUploadingDocuments(false);
      }
    };

    reader.readAsDataURL(file);
  };

  // Detect document tags based on filename
  const detectDocumentTags = (filename: string): string[] => {
    const tags = [];
    const lowerFilename = filename.toLowerCase();

    if (lowerFilename.includes('position') || lowerFilename.includes('policy')) {
      tags.push('position-paper');
    }
    if (lowerFilename.includes('research') || lowerFilename.includes('background')) {
      tags.push('research');
    }
    if (lowerFilename.includes('resolution') || lowerFilename.includes('draft')) {
      tags.push('resolution');
    }
    if (lowerFilename.includes('amendment')) {
      tags.push('amendment');
    }
    if (lowerFilename.includes('crisis') || lowerFilename.includes('emergency')) {
      tags.push('crisis');
    }

    return tags.length > 0 ? tags : ['general'];
  };

  // Update processing progress
  const setProcessingProgress = (filename: string, progress: number) => {
    const docIndex = documents.findIndex(doc => doc.filename === filename);
    if (docIndex !== -1) {
      removeDocument(documents[docIndex].id);
      addDocument({
        ...documents[docIndex],
        progress,
      });
    }
  };

  // Update document status
  const updateDocumentStatus = (filename: string, updates: Partial<UploadedDocument>) => {
    const docIndex = documents.findIndex(doc => doc.filename === filename);
    if (docIndex !== -1) {
      removeDocument(documents[docIndex].id);
      addDocument({
        ...documents[docIndex],
        ...updates,
      } as DocumentInfo);
    }
  };

  // Drag and drop handlers
  const handleDragEnter = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragging(true);
  };

  const handleDragLeave = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragging(false);
  };

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setIsDragging(false);
    handleFileSelect(e.dataTransfer.files);
  };

  // Format file size
  const formatFileSize = (bytes: number): string => {
    if (bytes < 1024) return bytes + ' B';
    if (bytes < 1024 * 1024) return Math.round(bytes / 1024) + ' KB';
    return Math.round(bytes / (1024 * 1024)) + ' MB';
  };

  // Get file type info
  const getFileInfo = (fileType: string) => {
    return allowedTypes[fileType as keyof typeof allowedTypes] || { name: 'Unknown', icon: '📄' };
  };

  return (
    <div className={`p-4 ${theme === 'dark' ? 'bg-gray-800' : 'bg-white'}`}>
      {/* Header */}
      <div className="mb-4">
        <h3 className={`text-lg font-semibold mb-2 ${
          theme === 'dark' ? 'text-white' : 'text-gray-900'
        }`}>
          Documents
        </h3>
        <p className={`text-sm ${
          theme === 'dark' ? 'text-gray-400' : 'text-gray-600'
        }`}>
          Upload and reference MUN documents
        </p>
      </div>

      {/* Upload Area */}
      <div
        className={`mb-4 border-2 border-dashed rounded-lg p-6 text-center transition-colors ${
          isDragging
            ? 'border-un-blue bg-un-blue/10'
            : theme === 'dark'
            ? 'border-gray-600 hover:border-gray-500'
            : 'border-gray-300 hover:border-gray-400'
        } ${uploadingDocuments ? 'opacity-50 cursor-not-allowed' : 'cursor-pointer'}`}
        onDragEnter={handleDragEnter}
        onDragLeave={handleDragLeave}
        onDragOver={handleDragOver}
        onDrop={handleDrop}
        onClick={() => !uploadingDocuments && fileInputRef.current?.click()}
      >
        <input
          ref={fileInputRef}
          type="file"
          multiple={false}
          accept={Object.keys(allowedTypes).join(',')}
          onChange={(e) => handleFileSelect(e.target.files)}
          className="hidden"
          disabled={uploadingDocuments}
        />

        <Upload
          size={48}
          className={`mx-auto mb-3 ${isDragging ? 'text-un-blue' : theme === 'dark' ? 'text-gray-400' : 'text-gray-500'}`}
        />
        <p className={`font-medium mb-1 ${
          theme === 'dark' ? 'text-white' : 'text-gray-900'
        }`}>
          {uploadingDocuments ? 'Processing...' : 'Drop document here or click to upload'}
        </p>
        <p className={`text-sm ${
          theme === 'dark' ? 'text-gray-400' : 'text-gray-600'
        }`}>
          PDF, Word, or text files (max 10MB)
        </p>
      </div>

      {/* Search and Filter */}
      <div className="mb-4 space-y-3">
        {/* Search */}
        <div className="relative">
          <Search
            size={18}
            className={`absolute left-3 top-1/2 transform -translate-y-1/2 ${
              theme === 'dark' ? 'text-gray-400' : 'text-gray-500'
            }`}
          />
          <input
            type="text"
            placeholder="Search documents..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className={`w-full pl-10 pr-4 py-2 rounded-lg border ${
              theme === 'dark'
                ? 'bg-gray-700 border-gray-600 text-white placeholder-gray-400'
                : 'bg-white border-gray-300 text-gray-900 placeholder-gray-500'
            } focus:ring-2 focus:ring-un-blue focus:border-transparent`}
          />
        </div>

        {/* Tag Filter */}
        {allTags.length > 0 && (
          <div className="flex items-center space-x-2 overflow-x-auto">
            <Tag
              size={16}
              className={theme === 'dark' ? 'text-gray-400' : 'text-gray-500'}
            />
            <button
              onClick={() => setSelectedTag('all')}
              className={`px-3 py-1 text-sm rounded-full whitespace-nowrap ${
                selectedTag === 'all'
                  ? 'bg-un-blue text-white'
                  : theme === 'dark'
                  ? 'bg-gray-700 text-gray-300'
                  : 'bg-gray-200 text-gray-700'
              }`}
            >
              All
            </button>
            {allTags.map(tag => (
              <button
                key={tag}
                onClick={() => setSelectedTag(tag)}
                className={`px-3 py-1 text-sm rounded-full whitespace-nowrap capitalize ${
                  selectedTag === tag
                    ? 'bg-un-blue text-white'
                    : theme === 'dark'
                    ? 'bg-gray-700 text-gray-300'
                    : 'bg-gray-200 text-gray-700'
                }`}
              >
                {tag.replace('-', ' ')}
              </button>
            ))}
          </div>
        )}
      </div>

      {/* Documents List */}
      <div className="space-y-2 max-h-96 overflow-y-auto">
        {filteredDocuments.length === 0 ? (
          <div className={`text-center py-8 ${
            theme === 'dark' ? 'text-gray-400' : 'text-gray-600'
          }`}>
            <FolderOpen size={48} className="mx-auto mb-3 opacity-50" />
            <p className="text-sm">
              {searchTerm || selectedTag !== 'all'
                ? 'No documents match your filters'
                : 'No documents uploaded yet'}
            </p>
          </div>
        ) : (
          filteredDocuments.map((doc) => {
            const fileInfo = getFileInfo(doc.fileType);
            const isProcessing = (doc as any).processing;

            return (
              <motion.div
                key={doc.id}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                className={`p-3 rounded-lg border ${
                  theme === 'dark'
                    ? 'bg-gray-700 border-gray-600'
                    : 'bg-gray-50 border-gray-200'
                } hover:shadow-md transition-all cursor-pointer`}
                onClick={() => setSelectedDocument(doc)}
              >
                <div className="flex items-start space-x-3">
                  {/* File Icon */}
                  <div className={`w-10 h-10 rounded-lg flex items-center justify-center text-lg ${
                    theme === 'dark' ? 'bg-gray-600' : 'bg-white'
                  }`}>
                    {fileInfo.icon}
                  </div>

                  {/* File Info */}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center justify-between mb-1">
                      <h4 className={`font-medium truncate ${
                        theme === 'dark' ? 'text-white' : 'text-gray-900'
                      }`}>
                        {doc.filename}
                      </h4>
                      <div className="flex items-center space-x-1">
                        {isProcessing ? (
                          <div className="w-2 h-2 bg-yellow-500 rounded-full animate-pulse" />
                        ) : doc.processed ? (
                          <CheckCircle size={16} className="text-green-500" />
                        ) : (
                          <AlertTriangle size={16} className="text-yellow-500" />
                        )}
                      </div>
                    </div>

                    <div className={`text-xs space-y-1 ${
                      theme === 'dark' ? 'text-gray-400' : 'text-gray-600'
                    }`}>
                      <div className="flex items-center justify-between">
                        <span>{fileInfo.name} • {formatFileSize(doc.fileSize)}</span>
                        <span>{new Date(doc.uploadedAt).toLocaleDateString()}</span>
                      </div>

                      {doc.contentSummary && (
                        <p className="truncate">{doc.contentSummary}</p>
                      )}

                      {/* Progress Bar */}
                      {isProcessing && (
                        <div className="w-full bg-gray-200 rounded-full h-1.5">
                          <div
                            className="bg-un-blue h-1.5 rounded-full transition-all duration-300"
                            style={{ width: `${(doc as any).progress || 0}%` }}
                          />
                        </div>
                      )}

                      {/* Tags */}
                      {doc.tags.length > 0 && (
                        <div className="flex flex-wrap gap-1">
                          {doc.tags.map(tag => (
                            <span
                              key={tag}
                              className={`px-2 py-0.5 text-xs rounded-full ${
                                theme === 'dark'
                                  ? 'bg-gray-600 text-gray-300'
                                  : 'bg-gray-200 text-gray-600'
                              } capitalize`}
                            >
                              {tag.replace('-', ' ')}
                            </span>
                          ))}
                        </div>
                      )}
                    </div>
                  </div>

                  {/* Actions */}
                  <div className="flex items-center space-x-1">
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        setSelectedDocument(doc);
                      }}
                      className={`p-1 rounded hover:bg-gray-100 dark:hover:bg-gray-600 ${
                        theme === 'dark' ? 'text-gray-400' : 'text-gray-600'
                      }`}
                    >
                      <Eye size={14} />
                    </button>
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        removeDocument(doc.id);
                      }}
                      className={`p-1 rounded hover:bg-red-100 dark:hover:bg-red-900/20 ${
                        theme === 'dark' ? 'text-gray-400' : 'text-gray-600'
                      }`}
                    >
                      <Trash2 size={14} />
                    </button>
                  </div>
                </div>
              </motion.div>
            );
          })
        )}
      </div>

      {/* Document Count */}
      {documents.length > 0 && (
        <div className={`mt-4 pt-4 border-t ${
          theme === 'dark' ? 'border-gray-700' : 'border-gray-200'
        }`}>
          <div className={`text-sm ${
            theme === 'dark' ? 'text-gray-400' : 'text-gray-600'
          }`}>
            {filteredDocuments.length} of {documents.length} documents
          </div>
        </div>
      )}

      {/* Document Preview Modal */}
      <AnimatePresence>
        {selectedDocument && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black bg-opacity-50 z-50 flex items-center justify-center p-4"
            onClick={() => setSelectedDocument(null)}
          >
            <motion.div
              initial={{ scale: 0.9, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.9, opacity: 0 }}
              className={`max-w-2xl w-full max-h-[90vh] overflow-y-auto ${
                theme === 'dark' ? 'bg-gray-800' : 'bg-white'
              } rounded-lg shadow-xl p-6`}
              onClick={(e) => e.stopPropagation()}
            >
              <div className="flex items-center justify-between mb-4">
                <h3 className={`text-lg font-semibold ${
                  theme === 'dark' ? 'text-white' : 'text-gray-900'
                }`}>
                  {selectedDocument.filename}
                </h3>
                <button
                  onClick={() => setSelectedDocument(null)}
                  className={`p-2 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-700`}
                >
                  <X size={20} />
                </button>
              </div>

              <div className="space-y-4">
                <div className={`p-4 rounded-lg ${
                  theme === 'dark' ? 'bg-gray-700' : 'bg-gray-100'
                }`}>
                  <h4 className={`font-medium mb-2 ${
                    theme === 'dark' ? 'text-white' : 'text-gray-900'
                  }`}>
                    Document Information
                  </h4>
                  <dl className={`text-sm space-y-2 ${
                    theme === 'dark' ? 'text-gray-300' : 'text-gray-700'
                  }`}>
                    <div className="flex justify-between">
                      <dt>Type:</dt>
                      <dd>{getFileInfo(selectedDocument.fileType).name}</dd>
                    </div>
                    <div className="flex justify-between">
                      <dt>Size:</dt>
                      <dd>{formatFileSize(selectedDocument.fileSize)}</dd>
                    </div>
                    <div className="flex justify-between">
                      <dt>Uploaded:</dt>
                      <dd>{new Date(selectedDocument.uploadedAt).toLocaleString()}</dd>
                    </div>
                    <div className="flex justify-between">
                      <dt>Status:</dt>
                      <dd>
                        {selectedDocument.processed ? (
                          <span className="text-green-500">Processed</span>
                        ) : (
                          <span className="text-yellow-500">Processing</span>
                        )}
                      </dd>
                    </div>
                  </dl>
                </div>

                {selectedDocument.contentSummary && (
                  <div>
                    <h4 className={`font-medium mb-2 ${
                      theme === 'dark' ? 'text-white' : 'text-gray-900'
                    }`}>
                      AI Summary
                    </h4>
                    <p className={`text-sm p-3 rounded-lg ${
                      theme === 'dark' ? 'bg-gray-700 text-gray-300' : 'bg-gray-100 text-gray-700'
                    }`}>
                      {selectedDocument.contentSummary}
                    </p>
                  </div>
                )}

                {selectedDocument.tags.length > 0 && (
                  <div>
                    <h4 className={`font-medium mb-2 ${
                      theme === 'dark' ? 'text-white' : 'text-gray-900'
                    }`}>
                      Tags
                    </h4>
                    <div className="flex flex-wrap gap-2">
                      {selectedDocument.tags.map(tag => (
                        <span
                          key={tag}
                          className={`px-3 py-1 text-sm rounded-full capitalize ${
                            theme === 'dark'
                              ? 'bg-gray-700 text-gray-300'
                              : 'bg-gray-200 text-gray-700'
                          }`}
                        >
                          {tag.replace('-', ' ')}
                        </span>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}